### ISSUE TITLE
Пример обращения к REST API из C#

### ISSUE THREAD

**Issue by uralbash** [ustu/lectures.www#27]
Добавить пеример взаимодействия C# с REST API при помощи класса ``HttpWebrequest``.

**Comment by AlekseiKrivo** [comment]
Студент Криво Алексей, группа ФО-340005

https://gist.github.com/AlekseiKrivo/fbbf18ea9d65db9f0c41fe43210f7d42

**Comment by uralbash** [comment]
Нужно оформить в виде vs проекта с осмысленным функционалом, например по адресу показывать координаты (геокодирование) и взять АПИ допустим Яндекса (https://tech.yandex.ru/maps/doc/geocoder/desc/concepts/input_params-docpage/). Помимо кода нужно подробное описание в в виде статьи.

**Comment by AlekseiKrivo** [comment]
Студент Криво Алексей, группа ФО-340005
Карты не вызвали особого интереса, реализовал приложение-переводчик с обращением к API Яндекс переводчика.
Исходные файлы приложения VS 2013, а также пояснительная записка находятся в репозитории YandexAPI:
https://github.com/AlekseiKrivo/YandexAPI
