### ISSUE TITLE
Написание чат ботов Telegram на языке Python

### ISSUE THREAD

**Issue by uralbash** [ustu/lectures.www#48]

**Comment by sashachabin** [comment]
Хотел бы рассказать про REST API на примере Telegram-ботов и сайта УрФУ:
https://core.telegram.org/bots/api
https://urfu.ru/api/

1-я часть доклада про разрабатываемого бота в Telegram, вместе с @FlaX89 (BeautifulSoup и Feedparser), @impuppy (SQLAlchemy) и @alex43jk (Pyramid).

**Comment by uralbash** [comment]
https://github.com/ustu/students/pull/731
https://github.com/ustu/students/pull/732
