### ISSUE TITLE
Реляционные БД

### ISSUE THREAD

**Issue by uralbash** [ustu/lectures.www#9]
@petrikoz 
Я думаю, можно заменить реляционную часть или дополнить лекциями Mike Bayer, https://bitbucket.org/zzzeek/pycon2013_student_package/src/a5b84d0659cbf1df11766fbbdc215dbe32be8044/handout/relational.html?at=master

Там готовый rst его можно скопировать и перевести.

**Comment by petrikoz** [comment]
Согласен. Он всё равно ближе к нашей специфике, чем то, что сейчас есть.

**Comment by petrikoz** [comment]
via 26f78bd
